lang: generic
branches:
  only:
  - source

install:
  - npm install hexo-cli -g
  - curl -sSL -o /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.24_Linux-64bit.deb

script:
  - make generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
